name: CI

on:
  push:
  pull_request:

defaults:
  run:
    shell: pwsh

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        persist-credentials: false
    - name: Setup psake
      run: Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name psake
    - name: Build
      run: invoke-psake build
    - name: Test
      run: |
        invoke-psake demo
        invoke-psake test